SET FOREIGN_KEY_CHECKS=0;

LOAD DATA LOCAL INFILE './loading_relations/data_files/brand.dat' INTO TABLE Brand FIELDS TERMINATED BY ',' ENCLOSED BY '' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './loading_relations/data_files/type.dat' INTO TABLE type FIELDS TERMINATED BY ',' ENCLOSED BY '' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './loading_relations/data_files/vehicle.dat' INTO TABLE Vehicle FIELDS TERMINATED BY ',' ENCLOSED BY '' LINES TERMINATED BY '\n';

SET FOREIGN_KEY_CHECKS=1;
